const playervalue = {
    "Kylian Mbappe": 160,
    "Erling Haaland": 150, 
    "Vinicius Junior": 120, 
    "Mohammed Salah": 110,
    "Harry Kane": 100, 
    "Phil Foden": 99, 
    "Bruno Fernandes": 96,
    "Kevin De Bruyne": 93,
    "Neymar": 90,
    "Dusan Vlahovic": 88,
    "Joshua Kimmich": 87,
    "Raheem Sterling": 86,
    "Romelu Lukaku": 85,
    "Pedri": 84,
    "Jadon Sancho": 83,
    "Trent Alexander Arnold": 82, 
    "Jack Grealish": 81, 
    "Sadio Mane": 80, 
    "Heung Min Son": 79, 
    "Jude Bellingham": 78, 
    "Declan Rice": 77, 
    "Mason Mount": 76, 
    "Ruben Dias": 75, 
    "Bernado Silva": 75, 
    "Marquinhos": 75, 
    "Florian Wirtz": 74, 
    "Joao Felix": 74, 
    "Alphonso Davies": 73, 
    "Lautaro Martinez": 73, 
    "Achraf Hakimi": 72, 
    "Rodri": 72, 
    "Mikel Oyarzabal": 71, 
    "Federico Chiesa": 71, 
    "Frenkie De Jong": 70, 
    "Matthijs De Ligt": 70, 
    "Kai Havertz": 69, 
    "Sergej Milinkovic Savic": 69, 
    "Marcus Rashford": 68,
    "Nicolo Barella": 68, 
    "Leroy Sane": 67, 
    "Serge Gnabry": 67, 
    "Leon Goeretzka": 66, 
    "Bukayo Saka": 66, 
    "Federico Valverde": 65, 
    "Christopher Nkunku": 65, 
    "Gianluigi Donnarumma": 64, 
    "Andrew Robertson": 64, 
    "Milan Skriniar": 63, 
    "Thibaut Courtois": 63, 
    "Gavi": 62,
    "Ansu Fati": 62,
    "Jules Kounde": 61, 
    "Victor Osihmen": 61, 
    "Eder Militao":60 , 
    "Diogo Jota": 60, 
    "Alessandro Bastoni": 60, 
    "Marcos Llorente": 59, 
    "Wilfred Ndidi": 59, 
    "Kingsley Coman": 59, 
    "Fabinho": 58, 
    "Joao Cancelo": 58, 
    "Raphael Varane": 58, 
    "Alisson": 57, 
    "Lionel Messi": 57, 
    "Eduardo Camavinga": 56, 
    "Reece James": 56, 
    "Moussa Diaby": 55, 
    "Fabian Ruiz": 55, 
    "Youri Tielemans": 55, 
    "Virgil Van Dijk": 54, 
    "Paul Pogba": 54, 
    "Marco Verrati": 54, 
    "David Alaba": 53, 
    "Jonathan David": 53, 
    "Amine Gouiri": 53, 
    "Pau Torres":, 
    "Richarlison", 
    "Carlos Soler", 
    "Gabriel Jesus", 
    "Rafael Leao", 
    "Arnaut Danjuma", 
    "Mikel Merino", 
    "James Maddison", 
    "Lucas Hernandez", 
    "Jose Maria Gimenez", 
    "Ngolo Kante", 
    "Antoine Griezmann", 
    "Robert Lewandowski", 
    "Casemiro", 
    "Theo Hernandez", 
    "Luis Diaz", 
    "Ferran Torres", 
    "Dayot Upamencano", 
    "Tammy Abraham", 
    "Diego Carlos", 
    "Caglar Söyuncu", 
    "Christian Pulisic", 
    "Fikayo Tomori", 
    "Franck Kessie", 
    "Dani Olmo", 
    "Lorenzo Pellegrini", 
    "Tomas Soucek",
    "Angel Correa", 
    "Aymeric Laporte", 
    "Memphis Depay", 
    "Jorginho", 
    "Kalidou Koulibaly", 
    "Marc-Andre ter Stegen", 
    "Mateo Kovacic", 
    "Giovanni Reyna", 
    "Martin Ödegaard", 
    "Dominic Calvert-Lewin", 
    "Luke Shaw", 
    "Timo Werner", 
    "Nuno Mendes", 
    "Edmond Tapsoba", 
    "Darwin Nunez", 
    "Aurelien Tchouameni", 
    "Rodrygo", 
    "Sandro Tonali", 
    "Emile Smith Rowe", 
    "Cristian Romero", 
    "Alexander Isak", 
    "Marco Asensio", 
    "Presnel Kimpembe", 
    "Rodrigo De Paul", 
    "Patrik Schick", 
    "Paulo Dybala", 
    "Harry Maguire", 
    "Gerard Moreno", 
    "Riyad Mahrez", 
    "Marcelo Brozovic", 
    "Wilfrid Zaha", 
    "Yannick Carrasco", 
    "Gabriel Martinelli", 
    "Ben Chilwell", 
    "Andre Silva", 
    "Roberto Firmino", 
    "Antony", 
    "Karim Adeyemi", 
    "Ryan Gravenberch", 
    "Tanguy Ndombele", 
    "Lucas Paqueta", 
    "Dejan Kulusevski",
    "Ollie Watkins",
    "Hirving Lozano",
    "Jarrod Bowen",
    "Robin Gosens",
    "Manuel Locatelli",
    "Ivan Toney",
    "Nabil Fekir",
    "Andreas Christensen",
    "Domenico Berardi",
    "Raphael Guerreiro",
    "Niklas Sule",
    "Hakan Calhanoglu",
    "Stefan de Vrij",
    "Antonio Rudiger",
    "Koke",
    "Ilkay Gundogan",
    "Cristiano Ronaldo",
    "Nicolo Zaniolo",
    "Lisandro Martinez",
    "Edouard Mendy",
    "Harvey Barnes",
    "Kieran Tierney",
    "Allan Saint Maximin",
    "Tyrone Mings",
    "Hakim Ziyech",
    "James Ward-Prowse",
    "Luis Alberto",
    "Matheus Nunes",
    "Bruno Guimaraes",
    "Matheus Cunha",
    "Gabriel",
    "Curtis Jones",
    "Jurrien Timber",
    "Houssem Aouar",
    "Leon Bailey",
    "Sven Botman",
    "Ibrahima Konate",
    "Benjamin Pavard",
    "Ismael Bennacer",
    "Robin Le Nordmand",
    "Davinson Sanchez",
    "Naby Keita",
    "Ousmane Dembele",
    "Manuel Akanji",
    "Renato Sanches",
    "Ruslan Malinkovskyi",
    "John McGinn",
    "Sebastian Haller",
    "Kurt Zouma",
    "Alvaro Morata",
    "Lucas Digne",
    "Ciro Immobile",
    "Duvan Zapata",
    "Dominik Szoboszlai",
    "Giacomo Raspadori",
    "Nico Schlotterbeck",
    "Evan Ndicka",
    "Sergio Reguilon",
    "Adama Traore",
    "John Stones",
    "Anthony Martial",
    "Andrea Belotti",
    "Saul Niguez",
    "Wissam Ben Yedder",
    "Mauro Icardi",
    "Ismaila Sarr",
    "Denis Zakaria",
    "Donyell Malen",
    "Matteo Politano",
    "Joaquin Correa",
    "Konrad Laimer",
    "Pedro Porro",
    "Bryan Gil",
    "Roger Ibanez",
    "Tino Livramento",
    "Conor Gallagher",
    "Renan Lodi",
    "Cody Gakpo",
    "Aaron Ramsdale",
    "Ezri Konza",
    "Boubacar Kamara",
    "Nordi Mukiele",
    "Weston McKennie",
    "Takehiro Tomiyasu",
    "Said Benrahma",
    "Donny van de Beek",
    "Inaki Williams",
    "Nelson Semedo",
    "Oleksandr Zinchenkon",
    "Julian Brandt"
    }

const playerArray = ["Kylian Mbappe",
"Erling Haaland", 
"Vinicius Junior", 
"Mohammed Salah",
"Harry Kane", 
"Phil Foden", 
"Bruno Fernandes",
"Kevin De Bruyne",
"Neymar",
"Dusan Vlahovic",
"Joshua Kimmich",
"Raheem Sterling",
"Romelu Lukaku",
"Pedri",
"Jadon Sancho",
"Trent Alexander Arnold", 
"Jack Grealish", 
"Sadio Mane", 
"Heung Min Son", 
"Jude Bellingham", 
"Declan Rice", 
"Mason Mount", 
"Ruben Dias", 
"Bernado Silva", 
"Marquinhos", 
"Florian Wirtz", 
"Joao Felix", 
"Alphonso Davies", 
"Lautaro Martinez", 
"Achraf Hakimi", 
"Rodri", 
"Mikel Oyarzabal", 
"Federico Chiesa", 
"Frenkie De Jong", 
"Matthijs De Ligt", 
"Kai Havertz", 
"Sergej Milinkovic Savic", 
"Marcus Rashford",
"Nicolo Barella", 
"Leroy Sane", 
"Serge Gnabry", 
"Leon Goeretzka", 
"Bukayo Saka", 
"Federico Valverde", 
"Christopher Nkunku", 
"Gianluigi Donnarumma", 
"Andrew Robertson", 
"Milan Skriniar", 
"Thibaut Courtois", 
"Gavi",
"Ansu Fati",
"Jules Kounde", 
"Victor Osihmen", 
"Eder Militao", 
"Diogo Jota", 
"Alessandro Bastoni", 
"Marcos Llorente", 
"Wilfred Ndidi", 
"Kingsley Coman", 
"Fabinho", 
"Joao Cancelo", 
"Raphael Varane", 
"Alisson", 
"Lionel Messi", 
"Eduardo Camavinga", 
"Reece James", 
"Moussa Diaby", 
"Fabian Ruiz", 
"Youri Tielemans", 
"Virgil Van Dijk", 
"Paul Pogba", 
"Marco Verrati", 
"David Alaba", 
"Jonathan David", 
"Amine Gouiri", 
"Pau Torres", 
"Richarlison", 
"Carlos Soler", 
"Gabriel Jesus", 
"Rafael Leao", 
"Arnaut Danjuma", 
"Mikel Merino", 
"James Maddison", 
"Lucas Hernandez", 
"Jose Maria Gimenez", 
"Ngolo Kante", 
"Antoine Griezmann", 
"Robert Lewandowski", 
"Casemiro", 
"Theo Hernandez", 
"Luis Diaz", 
"Ferran Torres", 
"Dayot Upamencano", 
"Tammy Abraham", 
"Diego Carlos", 
"Caglar Söyuncu", 
"Christian Pulisic", 
"Fikayo Tomori", 
"Franck Kessie", 
"Dani Olmo", 
"Lorenzo Pellegrini", 
"Tomas Soucek",
 "Angel Correa", 
 "Aymeric Laporte", 
 "Memphis Depay", 
 "Jorginho", 
 "Kalidou Koulibaly", 
 "Marc-Andre ter Stegen", 
 "Mateo Kovacic", 
 "Giovanni Reyna", 
 "Martin Ödegaard", 
 "Dominic Calvert-Lewin", 
 "Luke Shaw", 
 "Timo Werner", 
 "Nuno Mendes", 
 "Edmond Tapsoba", 
 "Darwin Nunez", 
 "Aurelien Tchouameni", 
 "Rodrygo", 
 "Sandro Tonali", 
 "Emile Smith Rowe", 
 "Cristian Romero", 
 "Alexander Isak", 
 "Marco Asensio", 
 "Presnel Kimpembe", 
 "Rodrigo De Paul", 
 "Patrik Schick", 
 "Paulo Dybala", 
 "Harry Maguire", 
 "Gerard Moreno", 
 "Riyad Mahrez", 
 "Marcelo Brozovic", 
 "Wilfrid Zaha", 
 "Yannick Carrasco", 
 "Gabriel Martinelli", 
 "Ben Chilwell", 
 "Andre Silva", 
 "Roberto Firmino", 
 "Antony", 
 "Karim Adeyemi", 
 "Ryan Gravenberch", 
 "Tanguy Ndombele", 
 "Lucas Paqueta", 
 "Dejan Kulusevski",
"Ollie Watkins",
"Hirving Lozano",
"Jarrod Bowen",
"Robin Gosens",
"Manuel Locatelli",
"Ivan Toney",
"Nabil Fekir",
"Andreas Christensen",
"Domenico Berardi",
"Raphael Guerreiro",
"Niklas Sule",
"Hakan Calhanoglu",
"Stefan de Vrij",
"Antonio Rudiger",
"Koke",
"Ilkay Gundogan",
"Cristiano Ronaldo",
"Nicolo Zaniolo",
"Lisandro Martinez",
"Edouard Mendy",
"Harvey Barnes",
"Kieran Tierney",
"Allan Saint Maximin",
"Tyrone Mings",
"Hakim Ziyech",
"James Ward-Prowse",
"Luis Alberto",
"Matheus Nunes",
"Bruno Guimaraes",
"Matheus Cunha",
"Gabriel",
"Curtis Jones",
"Jurrien Timber",
"Houssem Aouar",
"Leon Bailey",
"Sven Botman",
"Ibrahima Konate",
"Benjamin Pavard",
"Ismael Bennacer",
"Robin Le Nordmand",
"Davinson Sanchez",
"Naby Keita",
"Ousmane Dembele",
"Manuel Akanji",
"Renato Sanches",
"Ruslan Malinkovskyi",
"John McGinn",
"Sebastian Haller",
"Kurt Zouma",
"Alvaro Morata",
"Lucas Digne",
"Ciro Immobile",
"Duvan Zapata",
"Dominik Szoboszlai",
"Giacomo Raspadori",
"Nico Schlotterbeck",
"Evan Ndicka",
"Sergio Reguilon",
"Adama Traore",
"John Stones",
"Anthony Martial",
"Andrea Belotti",
"Saul Niguez",
"Wissam Ben Yedder",
"Mauro Icardi",
"Ismaila Sarr",
"Denis Zakaria",
"Donyell Malen",
"Matteo Politano",
"Joaquin Correa",
"Konrad Laimer",
"Pedro Porro",
"Bryan Gil",
"Roger Ibanez",
"Tino Livramento",
"Conor Gallagher",
"Renan Lodi",
"Cody Gakpo",
"Aaron Ramsdale",
"Ezri Konza",
"Boubacar Kamara",
"Nordi Mukiele",
"Weston McKennie",
"Takehiro Tomiyasu",
"Said Benrahma",
"Donny van de Beek",
"Inaki Williams",
"Nelson Semedo",
"Oleksandr Zinchenkon",
"Julian Brandt"]

export{playervalue, playerArray}