const playervalue = {
    "Anthony Modeste": 250,
    "Akinfenwa": 200,
    "Kylian Mbappe": 160,
    "Erling Haaland": 150, 
    "Vinicius Junior": 120, 
    "Mohamed Salah": 110,
    "Harry Kane": 100, 
    "Phil Foden": 99, 
    "Bruno Fernandes": 96,
    "Kevin De Bruyne": 93,
    "Neymar": 90,
    "Dusan Vlahovic": 88,
    "Joshua Kimmich": 87,
    "Raheem Sterling": 86,
    "Romelu Lukaku": 85,
    "Pedri": 84,
    "Jadon Sancho": 83,
    "Trent Alexander Arnold": 82, 
    "Jack Grealish": 81, 
    "Sadio Mane": 80, 
    "Heung Min Son": 79, 
    "Jude Bellingham": 78, 
    "Declan Rice": 77, 
    "Mason Mount": 76, 
    "Ruben Dias": 75, 
    "Bernardo Silva": 75, 
    "Marquinhos": 75, 
    "Florian Wirtz": 74, 
    "Joao Felix": 74, 
    "Alphonso Davies": 73, 
    "Lautaro Martinez": 73, 
    "Achraf Hakimi": 72, 
    "Rodri": 72, 
    "Mikel Oyarzabal": 71, 
    "Federico Chiesa": 71, 
    "Frenkie De Jong": 70, 
    "Matthijs De Ligt": 70, 
    "Kai Havertz": 69, 
    "Sergej Milinkovic Savic": 69, 
    "Marcus Rashford": 68,
    "Nicolo Barella": 68, 
    "Leroy Sane": 67, 
    "Serge Gnabry": 67, 
    "Leon Goeretzka": 66, 
    "Bukayo Saka": 66, 
    "Federico Valverde": 65, 
    "Christopher Nkunku": 65, 
    "Gianluigi Donnarumma": 64, 
    "Andrew Robertson": 64, 
    "Milan Skriniar": 63, 
    "Thibaut Courtois": 63, 
    "Ansu Fati": 62,
    "Jules Kounde": 61, 
    "Victor Osihmen": 61, 
    "Eder Militao":60 , 
    "Diogo Jota": 60, 
    "Alessandro Bastoni": 60, 
    "Marcos Llorente": 59, 
    "Wilfred Ndidi": 59, 
    "Kingsley Coman": 59, 
    "Fabinho": 58, 
    "Joao Cancelo": 58, 
    "Raphael Varane": 58, 
    "Alisson": 57, 
    "Lionel Messi": 57, 
    "Eduardo Camavinga": 56, 
    "Reece James": 56, 
    "Moussa Diaby": 55, 
    "Fabian Ruiz": 55, 
    "Youri Tielemans": 55, 
    "Virgil Van Dijk": 54, 
    "Paul Pogba": 54, 
    "Marco Verrati": 54, 
    "David Alaba": 53, 
    "Jonathan David": 53, 
    "Amine Gouiri": 53, 
    "Pau Torres": 52, 
    "Richarlison": 52, 
    "Carlos Soler": 52, 
    "Gabriel Jesus": 52, 
    "Rafael Leao": 51, 
    "Mikel Merino": 51, 
    "James Maddison": 50, 
    "Lucas Hernandez": 50, 
    "Jose Maria Gimenez": 49, 
    "Ngolo Kante": 49, 
    "Antoine Griezmann": 48, 
    "Robert Lewandowski":48, 
    "Casemiro": 47, 
    "Theo Hernandez": 47, 
    "Luis Diaz": 46, 
    "Ferran Torres": 46, 
    "Dayot Upamecano": 46, 
    "Tammy Abraham": 45, 
    "Diego Carlos": 45, 
    "Caglar Söyuncu": 45, 
    "Christian Pulisic": 44, 
    "Franck Kessie": 44, 
    "Dani Olmo": 44, 
    "Lorenzo Pellegrini": 44, 
    "Tomas Soucek": 43,
    "Angel Correa": 43, 
    "Aymeric Laporte": 43, 
    "Memphis Depay": 43, 
    "Jorginho": 43, 
    "Kalidou Koulibaly": 42, 
    "Marc-Andre ter Stegen": 42, 
    "Mateo Kovacic": 42, 
    "Giovanni Reyna": 42, 
    "Martin Ödegaard": 42, 
    "Dominic Calvert-Lewin": 41, 
    "Luke Shaw": 41, 
    "Timo Werner": 41, 
    "Nuno Mendes": 41, 
    "Darwin Nunez": 40, 
    "Aurelien Tchouameni": 40, 
    "Sandro Tonali": 40, 
    "Emile Smith Rowe": 40, 
    "Cristian Romero": 39, 
    "Marco Asensio": 39, 
    "Presnel Kimpembe": 39, 
    "Rodrigo De Paul": 39, 
    "Patrik Schick": 38, 
    "Paulo Dybala": 38, 
    "Harry Maguire": 2, 
    "Gerard Moreno": 38, 
    "Riyad Mahrez": 37, 
    "Marcelo Brozovic": 37, 
    "Wilfried Zaha": 37, 
    "Yannick Carrasco": 36, 
    "Gabriel Martinelli": 36, 
    "Ben Chilwell": 36, 
    "Andre Silva": 36, 
    "Roberto Firmino": 35, 
    "Antony": 35, 
    "Karim Adeyemi": 35, 
    "Ryan Gravenberch": 35, 
    "Tanguy Ndombele":35, 
    "Lucas Paqueta": 34, 
    "Dejan Kulusevski": 34,
    "Ollie Watkins": 34,
    "Hirving Lozano": 34,
    "Jarrod Bowen": 34,
    "Robin Gosens": 34,
    "Ivan Toney": 33,
    "Nabil Fekir": 33,
    "Andreas Christensen": 33,
    "Domenico Berardi": 33,
    "Raphael Guerreiro": 32,
    "Niklas Sule": 32,
    "Hakan Calhanoglu": 32,
    "Stefan de Vrij": 32,
    "Antonio Rudiger": 32,
    "Koke": 32,
    "Ilkay Gundogan": 31,
    "Cristiano Ronaldo": 31,
    "Nicolo Zaniolo": 31,
    "Lisandro Martinez": 31,
    "Edouard Mendy": 31,
    "Harvey Barnes": 31,
    "Kieran Tierney": 30,
    "Allan Saint-Maximin": 30,
    "Tyrone Mings": 30,
    "Hakim Ziyech": 30,
    "James Ward-Prowse": 30,
    "Luis Alberto": 30,
    "Matheus Nunes": 30,
    "Bruno Guimaraes": 29,
    "Matheus Cunha": 29,
    "Gabriel": 29,
    "Curtis Jones": 29,
    "Jurrien Timber": 29,
    "Houssem Aouar": 28,
    "Sven Botman": 28,
    "Ibrahima Konate": 28,
    "Benjamin Pavard": 28,
    "Ismael Bennacer": 27,
    "Robin Le Nordmand": 27,
    "Davinson Sanchez": 27,
    "Naby Keita": 27,
    "Ousmane Dembele": 27,
    "Manuel Akanji": 26,
    "Renato Sanches": 26,
    "Ruslan Malinkovskyi": 26,
    "John McGinn": 26,
    "Sebastien Haller": 26,
    "Kurt Zouma": 25,
    "Alvaro Morata": 25,
    "Lucas Digne": 25,
    "Ciro Immobile": 25,
    "Duvan Zapata": 25,
    "Dominik Szoboszlai": 24,
    "Giacomo Raspadori": 24,
    "Nico Schlotterbeck": 24,
    "Evan Ndicka": 24,
    "Sergio Reguilon": 24,
    "Adama Traore": 23,
    "John Stones": 23,
    "Anthony Martial": 23,
    "Andrea Belotti": 23,
    "Wissam Ben Yedder": 22,
    "Mauro Icardi": 22,
    "Denis Zakaria": 22,
    "Donyell Malen": 22,
    "Matteo Politano": 21,
    "Joaquin Correa": 21,
    "Konrad Laimer": 21,
    "Pedro Porro": 21,
    "Bryan Gil": 21,
    "Roger Ibanez": 20,
    "Tino Livramento": 20,
    "Conor Gallagher": 20,
    "Renan Lodi": 20,
    "Cody Gakpo": 20,
    "Aaron Ramsdale": 19,
    "Ezri Konza": 19,
    "Boubacar Kamara": 19,
    "Weston McKennie": 19,
    "Takehiro Tomiyasu": 18,
    "Said Benrahma": 18,
    "Donny van de Beek": 18,
    "Inaki Williams": 18,
    "Nelson Semedo": 18,
    "Oleksandr Zinchenko": 17,
    "Julian Brandt": 16
    }

const playerArray = ["Kylian Mbappe",
"Erling Haaland", 
"Vinicius Junior", 
"Mohamed Salah",
"Harry Kane", 
"Phil Foden", 
"Bruno Fernandes",
"Kevin De Bruyne",
"Neymar",
"Dusan Vlahovic",
"Joshua Kimmich",
"Raheem Sterling",
"Romelu Lukaku",
"Pedri",
"Jadon Sancho",
"Trent Alexander Arnold", 
"Jack Grealish", 
"Sadio Mane", 
"Heung Min Son", 
"Jude Bellingham", 
"Declan Rice", 
"Mason Mount", 
"Ruben Dias", 
"Bernardo Silva", 
"Marquinhos", 
"Florian Wirtz", 
"Joao Felix", 
"Alphonso Davies", 
"Lautaro Martinez", 
"Achraf Hakimi", 
"Rodri", 
"Mikel Oyarzabal", 
"Federico Chiesa", 
"Frenkie De Jong", 
"Matthijs De Ligt", 
"Kai Havertz", 
"Sergej Milinkovic Savic", 
"Marcus Rashford",
"Nicolo Barella", 
"Leroy Sane", 
"Serge Gnabry", 
"Leon Goeretzka", 
"Bukayo Saka", 
"Federico Valverde", 
"Christopher Nkunku", 
"Gianluigi Donnarumma", 
"Andrew Robertson", 
"Milan Skriniar", 
"Thibaut Courtois", 
"Ansu Fati",
"Jules Kounde", 
"Victor Osihmen", 
"Eder Militao", 
"Diogo Jota", 
"Alessandro Bastoni", 
"Marcos Llorente", 
"Wilfred Ndidi", 
"Kingsley Coman", 
"Fabinho", 
"Joao Cancelo", 
"Raphael Varane", 
"Alisson", 
"Lionel Messi", 
"Eduardo Camavinga", 
"Reece James", 
"Moussa Diaby", 
"Fabian Ruiz", 
"Youri Tielemans", 
"Virgil Van Dijk", 
"Paul Pogba", 
"Marco Verrati", 
"David Alaba", 
"Jonathan David", 
"Amine Gouiri", 
"Pau Torres", 
"Richarlison", 
"Carlos Soler", 
"Gabriel Jesus", 
"Rafael Leao",  
"Mikel Merino", 
"James Maddison", 
"Lucas Hernandez", 
"Jose Maria Gimenez", 
"Ngolo Kante", 
"Antoine Griezmann", 
"Robert Lewandowski", 
"Casemiro", 
"Theo Hernandez", 
"Luis Diaz", 
"Ferran Torres", 
"Dayot Upamecano", 
"Tammy Abraham", 
"Diego Carlos", 
"Caglar Söyuncu", 
"Christian Pulisic", 
"Franck Kessie", 
"Dani Olmo", 
"Lorenzo Pellegrini", 
"Tomas Soucek",
"Angel Correa", 
"Aymeric Laporte", 
"Memphis Depay", 
"Jorginho", 
"Kalidou Koulibaly", 
"Marc-Andre ter Stegen", 
"Mateo Kovacic", 
"Giovanni Reyna", 
"Martin Ödegaard", 
"Dominic Calvert-Lewin", 
"Luke Shaw", 
"Timo Werner", 
"Nuno Mendes",  
"Darwin Nunez", 
"Aurelien Tchouameni", 
"Sandro Tonali", 
"Emile Smith Rowe", 
"Cristian Romero", 
"Marco Asensio", 
"Presnel Kimpembe", 
"Rodrigo De Paul", 
"Patrik Schick", 
"Paulo Dybala", 
"Harry Maguire", 
"Gerard Moreno", 
"Riyad Mahrez",  
"Marcelo Brozovic", 
"Wilfried Zaha", 
"Yannick Carrasco", 
"Gabriel Martinelli", 
"Ben Chilwell",  
"Andre Silva", 
"Roberto Firmino", 
"Antony", 
"Karim Adeyemi", 
"Ryan Gravenberch", 
"Tanguy Ndombele", 
"Lucas Paqueta", 
"Dejan Kulusevski",
"Ollie Watkins",
"Hirving Lozano",
"Jarrod Bowen",
"Robin Gosens",
"Ivan Toney",
"Nabil Fekir",
"Andreas Christensen",
"Domenico Berardi",
"Raphael Guerreiro",
"Niklas Sule",
"Hakan Calhanoglu",
"Stefan de Vrij",
"Antonio Rudiger",
"Koke",
"Ilkay Gundogan",
"Cristiano Ronaldo",
"Nicolo Zaniolo",
"Lisandro Martinez",
"Edouard Mendy",
"Harvey Barnes",
"Kieran Tierney",
"Allan Saint-Maximin",
"Tyrone Mings",
"Hakim Ziyech",
"James Ward-Prowse",
"Luis Alberto",
"Matheus Nunes",
"Bruno Guimaraes",
"Matheus Cunha",
"Gabriel",
"Curtis Jones",
"Jurrien Timber",
"Houssem Aouar",
"Sven Botman",
"Ibrahima Konate",
"Benjamin Pavard",
"Ismael Bennacer",
"Robin Le Nordmand",
"Davinson Sanchez",
"Naby Keita",
"Ousmane Dembele",
"Manuel Akanji",
"Renato Sanches",
"Ruslan Malinkovskyi",
"John McGinn",
"Sebastien Haller",
"Kurt Zouma",
"Alvaro Morata",
"Lucas Digne",
"Ciro Immobile",
"Duvan Zapata",
"Dominik Szoboszlai",
"Giacomo Raspadori",
"Nico Schlotterbeck",
"Evan Ndicka",
"Sergio Reguilon",
"Adama Traore",
"John Stones",
"Anthony Martial",
"Andrea Belotti",
"Wissam Ben Yedder",
"Mauro Icardi",
"Denis Zakaria",
"Donyell Malen",
"Matteo Politano",
"Joaquin Correa",
"Konrad Laimer",
"Pedro Porro",
"Bryan Gil",
"Roger Ibanez",
"Tino Livramento",
"Conor Gallagher",
"Renan Lodi",
"Cody Gakpo",
"Aaron Ramsdale",
"Ezri Konza",
"Boubacar Kamara",
"Weston McKennie",
"Takehiro Tomiyasu",
"Said Benrahma",
"Donny van de Beek",
"Inaki Williams",
"Nelson Semedo",
"Oleksandr Zinchenko",
"Julian Brandt"]

export{playervalue, playerArray}